### PR TITLE
docs: add signing off on commits to PR template

### PR DESCRIPTION
**Pull request by psschwei**
### Which issue(s) does this pull-request address?

N/A

### Description

Adds an item to the pull request template for contributors to sign off on their commits

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [x] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [x] Tests are included 
- [x] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by ismaelfaro** [comment]
I just found that also we should add or have in consideration

> yarn docs:check

**Comment by ismaelfaro** [comment]
I vote to have a command that "apply al lint, format fixes", and another for "check tests and documentation".

**Comment by psschwei** [comment]
This might be a good case for adding some [pre-commit hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)

**Comment by vabarbosa** [comment]
there are pre-commit hooks: https://github.com/i-am-bee/bee-agent-framework/blob/main/.husky/pre-commit
however when working on a PR and commiting changes, i did run into multiple issues with the existing pre-commit hook.

for example,
- `Internal Error: bee-agent-framework@workspace:.: This package doesn't seem to be present in your lockfile`
- `Error: 'nwa' is not available. Either install it manually or install go/docker.`

i was to trackdown the problem and resolve but the experience was less than ideal.

my question is, do we really need all those scripts running in pre-commit (especially when [they already run as part of PR action](https://github.com/i-am-bee/bee-agent-framework/blob/main/.github/workflows/main.yml))?

they end up slowing down the git commit and introduce possible points of frustration, e.g., i dont believe i should [need `docker` and/or `go`](https://github.com/i-am-bee/bee-agent-framework/blob/main/scripts/copyright.sh) to be able to contribute

**Comment by Tomas2D** [comment]
The `pre-commit` hooks check for all the necessary things; if they pass, the pipeline will pass. Hook installation is triggered by the installation of dependencies, which is automatically done.

I do agree with @vabarbosa that COPYRIGHT script is pain, however I don't know about any other better package, if you or someone could do some research and brings a better solution it would be great.

Regarding `yarn docs:check` - it is part of the pre-commit hook, but `yarn docs:build` is not which we can discuss.

**Comment by JanPokorny** [comment]
@Tomas2D For copyright there's https://github.com/apache/skywalking-eyes

It's installable through Homebrew: https://formulae.brew.sh/formula/license-eye

**Comment by Tomas2D** [comment]
It would be great if we could enable docs links check only when there are some changes to markdown files.

**Comment by Tomas2D** [comment]
> @Tomas2D For copyright there's https://github.com/apache/skywalking-eyes
> 
> It's installable through Homebrew: https://formulae.brew.sh/formula/license-eye

We can switch to it.

**Review by Tomas2D — APPROVED** [review]

**Pull request merged**
