### PR TITLE
Examples for the llama 3.2 3B updated

### PR DESCRIPTION
**Pull request by Abiji-2020**
### Which issue(s) does this pull-request address?

Closes: #47 

### Description

Created an examples using the llama 3.2 3B model 

- This PR was done during Hactoberfest 2024

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [x] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [ ] Tests are included 
- [ ] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by Abiji-2020** [comment]
@Tomas2D sorry for the misleading error in the dependency due to the conflict in the yarn lock file I had removed a dependency.

**Comment by Abiji-2020** [comment]
@Tomas2D the dependency issue was resolved and the test was success.

**Comment by Abiji-2020** [comment]
@Tomas2D need help as the CI is failing for the previous commit messages. So how can I modify the previous commit messages?

**Comment by Tomas2D** [comment]
Use git rebase

**Pull request closed without merging**
