### PR TITLE
feat: add additional validation for DynamicTool

### PR DESCRIPTION
**Pull request by mhdawson**
### Which issue(s) does this pull-request address?

Closes: https://github.com/i-am-bee/bee-agent-framework/issues/77

### Description

Adds additional validation for construction of dynamic tools.
### Checklist

- [X] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [X] Linting passes: `yarn lint` or `yarn lint:fix`
- [X] Formatting is applied: `yarn format` or `yarn format:fix`
- [X] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [X] Tests are included 
- [ ] Documentation is changed or added
- [X] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

### CODE REVIEW

**Comment by mhdawson** [comment]
Note that instead of the regex suggested in https://github.com/i-am-bee/bee-agent-framework/issues/77 I tweaked to:
* allow _
* allow -
* allow 0

in addition to what was already allowed.

Some of the tests were using `_` and `-` characters and they seemed reasonable when naming a function, I also saw no reason why 0 would not be accepted in terms of numbers.

**Comment by mhdawson** [comment]
As an FYI I'm away until next Monday, so I won't respond to any comments/suggestions until I get back on Oct 21st.

A doc update might make sense for the restrictions on the tool name, but would like to get confirmation that the adjusted validation I have in the PR is what's wanted before I look at updating the docs. Also happy to update the docs in a followon PR.

**Comment by mhdawson** [comment]
In terms of the e2e tests, is there an easy way to specify a remote ollama instance instead of the default running on the same machine? 

It also seems to want an API key for some of the tests?

```
Error: No API key for any LLM provider has been provided. Cannot run test case.
 ❯ Module.createChatLLM tests/utils/llmFactory.ts:39:11
     37|     });
     38|   } else {
     39|     throw new Error("No API key for any LLM provider has been provided. Cannot run test case.");
       |           ^
     40|   }
     41| }
```

**Comment by mhdawson** [comment]
Back now, just waiting on feedback on changes to the regex before looking at updating the docs.

**Comment by mhdawson** [comment]
Rebased.

**Review by Tomas2D — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
